// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsv-jF2ro_3bOsFF2k3wePo1bxweuwq_A',
    appId: '1:507665559579:web:b6bce8916e6335754e88be',
    messagingSenderId: '507665559579',
    projectId: 'm-health-4cab9',
    authDomain: 'm-health-4cab9.firebaseapp.com',
    storageBucket: 'm-health-4cab9.firebasestorage.app',
    measurementId: 'G-QSETXL7V92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBat9tA9p4ggcV-UK_ATLJK-XKNQZxMOpI',
    appId: '1:507665559579:android:c0453e2b29d5070f4e88be',
    messagingSenderId: '507665559579',
    projectId: 'm-health-4cab9',
    storageBucket: 'm-health-4cab9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjiAga7ptWJAbZrsS25Cm719aPAsZAcE0',
    appId: '1:507665559579:ios:06c4b298f4ef3a0a4e88be',
    messagingSenderId: '507665559579',
    projectId: 'm-health-4cab9',
    storageBucket: 'm-health-4cab9.firebasestorage.app',
    iosBundleId: 'com.example.studentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjiAga7ptWJAbZrsS25Cm719aPAsZAcE0',
    appId: '1:507665559579:ios:06c4b298f4ef3a0a4e88be',
    messagingSenderId: '507665559579',
    projectId: 'm-health-4cab9',
    storageBucket: 'm-health-4cab9.firebasestorage.app',
    iosBundleId: 'com.example.studentApp',
  );
}
